### ISSUE TITLE
Throws NotSupportedException when run

### ISSUE THREAD

**Issue by oniony** [dotnet/codeformatter#73]
I've just tried running CodeFormatter at itself and at a noddy solution and both times it threw the following exception:

    Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NotSupportedException: Changingparse options is not supported.
       at Microsoft.CodeAnalysis.Workspace.CheckAllowedProjectChanges(ProjectChanges projectChanges)
       at Microsoft.CodeAnalysis.Workspace.CheckAllowedSolutionChanges(SolutionChanges solutionChanges)
       at Microsoft.CodeAnalysis.Workspace.TryApplyChanges(Solution newSolution)
       at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.TryApplyChanges(Solution newSolution)
       at Microsoft.DotNet.CodeFormatting.FormattingEngineImplementation.<FormatAsync>d__1.MoveNext() in D:\WorkingCopy\ThirdParty\codeformatter\src\Microsoft.DotNet.CodeFormatting\FormattingEngineImplementation.cs:line 97
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at CodeFormatter.Program.<RunAsync>d__1.MoveNext() in D:\WorkingCopy\ThirdParty\codeformatter\src\CodeFormatter\Program.cs:line 139
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait(CancellationToken cancellationToken)
       at CodeFormatter.Program.Main(String[] args) in D:\WorkingCopy\ThirdParty\codeformatter\src\CodeFormatter\Program.cs:line 110

This is with commit `3fd4df0d7dcca8023fc20271d960d0326b75979b`.

**Comment by jaredpar** [comment]
A couple of users have reported this now but we are having some problems tracking it down.  Can you give me a bit more info here?

- Can you provide the exact command line used? 
- What versions of Visual Studio and MSBuild are installed on the machine?

**Comment by oniony** [comment]
I am running it, for example, like this:

    d:\WorkingCopy\ThirdParty\codeformatter>src\CodeFormatter\bin\Debug\CodeFormatter.exe src\CodeFormatter.sln

I just today installed the Visual Studio 2015 Preview (14.0.22310.1 DP). The framework version reported by Visual Studio is 4.5.53349.

Here is my NuGet cache:

![image](https://cloud.githubusercontent.com/assets/5895/6305217/6a4642ce-b921-11e4-9266-e1517f12bf3e.png)

**Comment by oniony** [comment]
D:\WorkingCopy\ThirdParty\codeformatter>msbuild
    Microsoft (R) Build Engine version 14.0.22310.1

**Comment by jaredpar** [comment]
Thanks for the extra info.  I'm going to be looking into this over the weekend.
